### PR TITLE
fix HA2024.8.0 fan entity features compatibility

### PR DESCRIPTION
**Pull request by litinoveweedle**
Hello,

please find PR to fix latest HA 2024.8.0 compatibility fix for fan entity - for more see https://developers.home-assistant.io/blog/2024/07/19/fan-fanentityfeatures-turn-on_off/

### CODE REVIEW

**Comment by litinoveweedle** [comment]
OK, may I use Black formater do get rid of the formatting issues? It will reformat more of your original code, but I would suggest to add it to your CI anyways for PR/Push

**Comment by michaelarnauts** [comment]
The repo is using ruff for formatting, so I think it will complain unless you use that.

**Comment by litinoveweedle** [comment]
well the best practice is to enforce your formater in the CI run in the PR - this way you and the contributors do not need to take care about formatting manually. But now it seems to be passing...

**Comment by michaelarnauts** [comment]
Sorry for the delay.

I've added the `ruff format --check` command to the Makefile, so it also checks if the format has been applied correctly. Apparently, I was only checking for linting errors, but not if the files had been formatted according to the ruff rules.

**Comment by michaelarnauts** [comment]
Thanks @litinoveweedle

**Comment by litinoveweedle** [comment]
@michaelarnauts You are very welcome, thank you for your work! ;-)

**Pull request merged**
